language: cpp

sudo: false

matrix:
    include:
        - os: linux
          compiler: gcc
          env: INSTALL_CXX=g++-4.8
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test' ]
                packages: [ 'g++-4.8' ]
        - os: linux
          compiler: gcc
          env: INSTALL_CXX=g++-4.9
          addons:
            apt:
                sources: [ 'ubuntu-toolchain-r-test' ]
                packages: [ 'g++-4.9' ]

before_install:
    - if [ -n "${INSTALL_CXX}" ]; then CXX=${INSTALL_CXX}; fi
    - chmod +x travis_script.sh

script:
    - $CXX --version
    - $CC --version
    - ./travis_script.sh
