language: c++

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - clang

before_install:
  - chmod +x travis_script.sh

script:
  - ./travis_script.sh
